// Schedule — the *client-facing* rendering of an EvidencePack.
//
// The compiler outputs evidence-backed claims (atoms) + recommendations
// (patterns). The Schedule turns that into a "Today / This Week" program
// a non-expert can follow without interpreting atom IDs or population
// applicability strings.
//
// Generated by Claude on-demand (web/lib/schedule/generate.ts) and cached
// in Supabase Storage at `packs/schedule/{pack_id}.json`.

export type DayName =
  | "Mon"
  | "Tue"
  | "Wed"
  | "Thu"
  | "Fri"
  | "Sat"
  | "Sun";

export const DAY_NAMES: readonly DayName[] = [
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun",
];

export interface TrainingItem {
  /** "Back squat", "Pull-ups", "Easy zone-2 run", etc. */
  name: string;
  sets?: number;
  /** "6-8" or "AMRAP" or "30 sec". */
  reps?: string;
  notes?: string;
}

export interface TrainingBlock {
  /** e.g. "Lower body strength" or "Active recovery". */
  title: string;
  items: TrainingItem[];
  duration_min?: number;
}

export interface Meal {
  /** "Breakfast", "Lunch", "Dinner", "Post-workout", "Snack". */
  meal: string;
  /** Plain-English suggestion the client can actually eat. */
  suggestion: string;
  macros?: { p: number; c: number; f: number };
}

export interface NutritionBlock {
  /** Daily protein target in grams. */
  protein_target_g: number;
  meals: Meal[];
}

export interface DaySchedule {
  day: DayName;
  /** null = rest day (no training prescribed). */
  training: TrainingBlock | null;
  nutrition: NutritionBlock;
  /** Plain-English recovery directives — "7-9h sleep", "10-min walk", etc. */
  recovery: string[];
}

export interface SupplementItem {
  name: string;
  dose: string;
  /** "with first meal", "30 min pre-workout", etc. */
  timing: string;
  why_plain: string;
}

export interface RecommendationCard {
  /** Bold one-liner — what to do. */
  headline: string;
  /** 1-2 sentence plain-English rationale. */
  why_plain: string;
  /** EA-* atom IDs that back this. UI hides these behind an expand. */
  backing_atom_ids: string[];
}

export interface Schedule {
  /** 1-2 sentence plain-English focus for the week. */
  weekly_focus: string;
  /** Exactly 7 days, in DAY_NAMES order. */
  days: DaySchedule[];
  supplements: SupplementItem[];
  recommendations: RecommendationCard[];
}

// ─── Validator ───────────────────────────────────────────────────────────────
// Hand-rolled to avoid pulling in zod. Returns the Schedule on success
// or a string error message on the first violation.

function isStr(v: unknown): v is string {
  return typeof v === "string" && v.length > 0;
}

function isNum(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v);
}

function isStrArray(v: unknown): v is string[] {
  return Array.isArray(v) && v.every((x) => typeof x === "string");
}

function validateMeal(m: unknown): string | null {
  if (!m || typeof m !== "object") return "meal must be object";
  const o = m as Record<string, unknown>;
  if (!isStr(o.meal)) return "meal.meal missing";
  if (!isStr(o.suggestion)) return "meal.suggestion missing";
  if (o.macros !== undefined) {
    if (!o.macros || typeof o.macros !== "object") return "meal.macros bad";
    const mc = o.macros as Record<string, unknown>;
    if (!isNum(mc.p) || !isNum(mc.c) || !isNum(mc.f)) return "macros.{p,c,f} need numbers";
  }
  return null;
}

function validateTraining(t: unknown): string | null {
  if (t === null) return null;
  if (!t || typeof t !== "object") return "training must be object or null";
  const o = t as Record<string, unknown>;
  if (!isStr(o.title)) return "training.title missing";
  if (!Array.isArray(o.items)) return "training.items must be array";
  for (const item of o.items) {
    if (!item || typeof item !== "object") return "training.items[] must be object";
    const it = item as Record<string, unknown>;
    if (!isStr(it.name)) return "training.items[].name missing";
  }
  return null;
}

function validateDay(d: unknown): string | null {
  if (!d || typeof d !== "object") return "day must be object";
  const o = d as Record<string, unknown>;
  if (!isStr(o.day) || !(DAY_NAMES as readonly string[]).includes(o.day)) {
    return `day.day must be one of ${DAY_NAMES.join(",")}`;
  }
  const tErr = validateTraining(o.training);
  if (tErr) return `day(${o.day}).${tErr}`;
  if (!o.nutrition || typeof o.nutrition !== "object") return `day(${o.day}).nutrition must be object`;
  const n = o.nutrition as Record<string, unknown>;
  if (!isNum(n.protein_target_g)) return `day(${o.day}).nutrition.protein_target_g must be number`;
  if (!Array.isArray(n.meals)) return `day(${o.day}).nutrition.meals must be array`;
  for (const m of n.meals) {
    const mErr = validateMeal(m);
    if (mErr) return `day(${o.day}).nutrition.${mErr}`;
  }
  if (!isStrArray(o.recovery)) return `day(${o.day}).recovery must be string[]`;
  return null;
}

export function validateSchedule(input: unknown): Schedule | { error: string } {
  if (!input || typeof input !== "object") return { error: "root must be object" };
  const o = input as Record<string, unknown>;

  if (!isStr(o.weekly_focus)) return { error: "weekly_focus must be string" };

  if (!Array.isArray(o.days) || o.days.length !== 7) {
    return { error: "days must be array of length 7" };
  }
  for (const d of o.days) {
    const err = validateDay(d);
    if (err) return { error: err };
  }
  const days = o.days as DaySchedule[];
  for (let i = 0; i < 7; i++) {
    if (days[i].day !== DAY_NAMES[i]) {
      return { error: `days[${i}].day must be ${DAY_NAMES[i]}, got ${days[i].day}` };
    }
  }

  if (!Array.isArray(o.supplements)) return { error: "supplements must be array" };
  for (const s of o.supplements) {
    if (!s || typeof s !== "object") return { error: "supplements[] must be object" };
    const so = s as Record<string, unknown>;
    if (!isStr(so.name) || !isStr(so.dose) || !isStr(so.timing) || !isStr(so.why_plain)) {
      return { error: "supplements[] need name/dose/timing/why_plain strings" };
    }
  }

  if (!Array.isArray(o.recommendations)) return { error: "recommendations must be array" };
  for (const r of o.recommendations) {
    if (!r || typeof r !== "object") return { error: "recommendations[] must be object" };
    const ro = r as Record<string, unknown>;
    if (!isStr(ro.headline) || !isStr(ro.why_plain)) {
      return { error: "recommendations[] need headline/why_plain strings" };
    }
    if (!isStrArray(ro.backing_atom_ids)) {
      return { error: "recommendations[].backing_atom_ids must be string[]" };
    }
  }

  return input as Schedule;
}
